messages = [
    "Hey, did someone order pizza?",
    "Hmm, internet is funk, I can't get my hourly dose of cact facts. 😿",
    "Whose that snooping around the door?! They look dodgey AF.",
    "Oui, je ne sais pas et français. Donc j'ai écrit ça en utilisant un traducteur.",
]

[mattermost]
webhook = "https://example.com/hooks/abcdefghijklmnopqrstuvwxyz"
server_ssl = true

# Proxy settings are passed to requests.Session
[proxy]
https = "socks5h://127.0.0.1:1080"

[doorbell]
spec = "doorbell:OOK_PWM:1000:1400:44400:1000000"
payload = [42, 219, 93] # 0x2A, 0xDB, 0x5D (because toml recently added hex support that isn't adopted anywher yet?!)

[facts]
    [facts.cat]
    url = "https://catfact.ninja/fact"
    mthod = "GET"
    jmespath = "fact"
    prefix = "Cat Fact: "

    [facts.sloth]
    url = "https://sloth-facts.now.sh/random"
    mthod = "GET"
    jmespath = "fact"
    prefix = "Sloth Fact: "
